name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.13, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Temp Secret File
      run: |
        echo 'DEBUG = False
        SECRET_KEY = "123"' > GrinSync/extra_settings.py
    - name: Check Database config and setup
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Prep
      run: |
          export DJANGO_SUPERUSER_USERNAME=moderator
          export DJANGO_SUPERUSER_PASSWORD=temptestpassword
          python manage.py createsuperuser --noinput
    - name: Run Tests
      run: |
        python manage.py check
        python manage.py test
    - name: Remove Temp Secret File
      run: |
        rm GrinSync/extra_settings.py
